version: '3.4'

networks:
  app:

services:
  mongo_service:
    container_name: mongodb
    image: mongo:latest
    expose:
      - 27017 #pour fermer depuis l'exterieur du docker network
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${pass}
    networks:
      - app

  fizzbuzz_service:
    container_name: fizzbuzz_app
    image: fizzbuzz:v2.0
    build:
      context: .
      dockerfile: ./dockerfile-app
    networks:
      - app
    volumes:
      - ./app:/app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${pass}
      ME_CONFIG_MONGODB_URL: ${url}
    command: bash
    tty: true
    depends_on:
      - mongo_service